# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - "/home/gitlab-runner/.nvm/versions/node/v8.12.0/bin/npm install"
    - "/home/gitlab-runner/.nvm/versions/node/v8.12.0/bin/npm run build"
  artifacts:
    paths:
    - lib
  only:
  - master
