# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - "echo $HOME"
    - "whoami"
    - "export PATH=\"$HOME/bin:$HOME/.local/bin:$NVM_BIN:$PATH\""
    - "env | grep PATH"
    - "npm install"
    - "npm run build"
  artifacts:
    paths:
    - lib
  only:
  - master
