# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - "echo $HOME"
    - "whoami"
    - "PATH=\"$HOME/bin:$HOME/.local/bin:$PATH\" && npm install"
    - "PATH=\"$HOME/bin:$HOME/.local/bin:$PATH\" && npm run build"
  artifacts:
    paths:
    - lib
  only:
  - master
